import io
import os
import json
import re
from typing import Dict, Any, List
from PyPDF2 import PdfReader
import docx
import requests
from dotenv import load_dotenv

import schemas

load_dotenv()

# ==========================================
# 1. DOCUMENT TEXT EXTRACTION
# ==========================================

def extract_text_from_pdf(file_bytes: bytes) -> str:
    try:
        reader = PdfReader(io.BytesIO(file_bytes))
        text = ""
        for page in reader.pages:
            page_text = page.extract_text()
            if page_text:
                text += page_text + "\n"
        return text
    except Exception as e:
        print(f"Error reading PDF: {e}")
        return ""

def extract_text_from_docx(file_bytes: bytes) -> str:
    try:
        doc = docx.Document(io.BytesIO(file_bytes))
        text = "\n".join([para.text for para in doc.paragraphs if para.text])
        return text
    except Exception as e:
        print(f"Error reading DOCX: {e}")
        return ""

def extract_text(file_bytes: bytes, filename: str) -> str:
    if filename.lower().endswith('.pdf'):
        return extract_text_from_pdf(file_bytes)
    elif filename.lower().endswith('.docx'):
        return extract_text_from_docx(file_bytes)
    return ""

# ==========================================
# 2. ROBUST TEXT CHUNKER (Built-in + LangChain)
# ==========================================

def chunk_text(text: str, chunk_size: int = 500, chunk_overlap: int = 80) -> List[str]:
    try:
        from langchain_text_splitters import RecursiveCharacterTextSplitter
        splitter = RecursiveCharacterTextSplitter(chunk_size=chunk_size, chunk_overlap=chunk_overlap)
        return [doc.page_content for doc in splitter.create_documents([text])]
    except Exception:
        pass

    try:
        from langchain.text_splitter import RecursiveCharacterTextSplitter
        splitter = RecursiveCharacterTextSplitter(chunk_size=chunk_size, chunk_overlap=chunk_overlap)
        return [doc.page_content for doc in splitter.create_documents([text])]
    except Exception:
        pass

    # Native Python semantic chunker
    paragraphs = [p.strip() for p in text.split("\n") if p.strip()]
    chunks = []
    current_chunk = ""
    for p in paragraphs:
        if len(current_chunk) + len(p) < chunk_size:
            current_chunk += "\n" + p
        else:
            if current_chunk:
                chunks.append(current_chunk.strip())
            current_chunk = p
    if current_chunk:
        chunks.append(current_chunk.strip())
    return chunks if chunks else [text]

# ==========================================
# 3. MULTI-MODEL GEMINI INVOCATION ENGINE
# ==========================================

ACTIVE_GEMINI_MODELS = [
    "gemini-flash-lite-latest",
    "gemini-flash-latest",
    "gemini-2.5-flash-lite",
    "gemma-4-26b-a4b-it"
]

def _call_gemini_with_fallback(api_key: str, prompt: str) -> str:
    """Tries active Gemini models with automatic fallback if one is busy (503/429)."""
    last_err = None
    for model_name in ACTIVE_GEMINI_MODELS:
        try:
            url = f"https://generativelanguage.googleapis.com/v1beta/models/{model_name}:generateContent?key={api_key}"
            payload = {
                "contents": [{"parts": [{"text": prompt}]}],
                "generationConfig": {"temperature": 0.2, "maxOutputTokens": 2048}
            }
            resp = requests.post(url, json=payload, timeout=25)
            if resp.status_code == 200:
                data = resp.json()
                cand = data.get("candidates", [{}])[0]
                text = cand.get("content", {}).get("parts", [{}])[0].get("text", "")
                if text.strip():
                    print(f"[AI Service] Successfully generated insights using {model_name}")
                    return text
            else:
                print(f"[AI Service] Model {model_name} returned status {resp.status_code}")
                last_err = f"Status {resp.status_code}: {resp.text[:120]}"
        except Exception as e:
            print(f"[AI Service] Model {model_name} error: {e}")
            last_err = str(e)
            
    raise RuntimeError(f"All Gemini models exhausted. Last error: {last_err}")

# ==========================================
# 4. JSON RESPONSE PARSER & CLEANER
# ==========================================

def _clean_and_parse_json(raw_text: str) -> Dict[str, Any]:
    cleaned = raw_text.strip()
    if "```json" in cleaned:
        cleaned = cleaned.split("```json")[1].split("```")[0].strip()
    elif "```" in cleaned:
        cleaned = cleaned.split("```")[1].split("```")[0].strip()

    first_brace = cleaned.find("{")
    last_brace = cleaned.rfind("}")
    if first_brace != -1 and last_brace != -1:
        cleaned = cleaned[first_brace:last_brace + 1]

    # Fix invalid escapes sometimes generated by LLMs
    cleaned = re.sub(r'\\([^\/\\bfnrt"])', r'\\\\\1', cleaned)

    return json.loads(cleaned, strict=False)

# ==========================================
# 5. FALLBACK HEURISTIC GENERATOR
# ==========================================

def generate_fallback_heuristic_analysis(text: str) -> Dict[str, Any]:
    if not text.strip():
        return {
            "overall_score": 0,
            "ats_score": 0,
            "skill_match": 0,
            "issues_found": 5,
            "ai_summary": "Empty resume file uploaded. No text could be extracted.",
            "ats_feedback": "Document contains no readable text layers. Ensure standard PDF/DOCX export.",
            "action_verb_feedback": "No action verbs detected.",
            "bullet_suggestions": [],
            "missing_keywords": ["Experience", "Skills", "Education", "Projects"],
            "strengths": [],
            "improvements": ["Upload a non-empty, text-searchable resume file."]
        }
        
    text_lower = text.lower()
    words = text_lower.split()
    word_count = len(words)
    
    sections = ['experience', 'education', 'skills', 'projects', 'summary', 'objective']
    found_sections = [sec for sec in sections if sec in text_lower]
    section_score = min(100, (len(found_sections) / 4) * 100)
    
    action_verbs = ['developed', 'managed', 'created', 'led', 'designed', 'implemented', 'improved', 'increased', 'reduced', 'optimized', 'spearheaded', 'orchestrated']
    found_verbs = [verb for verb in action_verbs if verb in text_lower]
    verb_score = min(100, (len(found_verbs) / 5) * 100)
    
    has_numbers = bool(re.search(r'\d+', text))
    has_percentages = bool(re.search(r'\d+%', text))
    has_currency = bool(re.search(r'\$\d+', text))
    
    metrics_score = 0
    if has_numbers: metrics_score += 40
    if has_percentages: metrics_score += 30
    if has_currency: metrics_score += 30
    
    length_score = 100
    if word_count < 200: length_score = 50
    elif word_count > 1000: length_score = 70
        
    overall_score = round(min(max((section_score * 0.3) + (verb_score * 0.3) + (metrics_score * 0.2) + (length_score * 0.2), 20), 96), 1)
    ats_score = round(min(max((section_score * 0.6) + (length_score * 0.4), 25), 98), 1)
    skill_match = round(min(max((verb_score * 0.4) + (section_score * 0.6), 20), 95), 1)
    
    issues_count = 0
    if len(found_sections) < 4: issues_count += 1
    if len(found_verbs) < 4: issues_count += 1
    if not has_numbers: issues_count += 1
    if word_count < 250 or word_count > 900: issues_count += 1
    if not (has_percentages or has_currency): issues_count += 1

    return {
        "overall_score": overall_score,
        "ats_score": ats_score,
        "skill_match": skill_match,
        "issues_found": max(issues_count, 1),
        "ai_summary": f"Resume analysis extracted {word_count} words across key sections ({', '.join(found_sections) if found_sections else 'general'}). The document showcases relevant background but would benefit from greater metric quantification and targeted keyword expansion.",
        "ats_feedback": f"Standard section headers detected: {len(found_sections)}/6. Ensure clean single-column hierarchy for optimal ATS parsing.",
        "action_verb_feedback": f"Found {len(found_verbs)} high-impact action verbs. Aim to start every bullet with strong velocity verbs like 'Architected', 'Spearheaded', or 'Optimized'.",
        "bullet_suggestions": [
            {
                "original": "Responsible for managing tasks and working with the engineering team.",
                "improved": "Spearheaded Agile sprint execution with 6 engineers, accelerating feature shipping cadence by 30%.",
                "reason": "Replaces passive duty statement with quantified business impact."
            }
        ],
        "missing_keywords": ["CI/CD Pipelines", "System Architecture", "KPI Tracking", "Cross-Functional Leadership"],
        "strengths": [
            f"Clear section division with {len(found_sections)} standard resume sections.",
            "Adequate overall word count volume for scanning.",
            "Logical chronological presentation."
        ],
        "improvements": [
            "Add quantifiable business metrics (%, $, volume) to every project bullet.",
            "Incorporate more industry-specific technical keywords.",
            "Replace passive phrasing with active leadership verbs."
        ]
    }

# ==========================================
# 6. MAIN RAG + GEMINI LLM ANALYSIS PIPELINE
# ==========================================

def analyze_resume_with_rag(text: str) -> Dict[str, Any]:
    api_key = os.getenv("GOOGLE_API_KEY", "").strip()
    if not api_key:
        print("[AI Service] No GOOGLE_API_KEY set in backend/.env. Using fallback analysis.")
        return generate_fallback_heuristic_analysis(text)

    # 1. Chunk document
    chunks = chunk_text(text, chunk_size=500, chunk_overlap=80)

    # 2. Vector Retrieval (RAG)
    rag_context = ""
    try:
        from langchain_google_genai import GoogleGenerativeAIEmbeddings
        from langchain_community.vectorstores import FAISS
        from langchain_core.documents import Document

        doc_objs = [Document(page_content=c) for c in chunks]
        embeddings = GoogleGenerativeAIEmbeddings(model="models/gemini-embedding-001", google_api_key=api_key)
        vectorstore = FAISS.from_documents(doc_objs, embeddings)
        retriever = vectorstore.as_retriever(search_kwargs={"k": 4})

        q1 = retriever.invoke("Work experience accomplishments metrics percentages leadership")
        q2 = retriever.invoke("Skills technical tools technologies certifications education")
        q3 = retriever.invoke("Key projects bullet points achievements responsibilities")

        all_retrieved = {d.page_content for d in (q1 + q2 + q3)}
        rag_context = "\n---\n".join(all_retrieved)
        print("[AI Service] RAG vector context retrieved successfully via FAISS.")
    except Exception as rag_err:
        print(f"[AI Service] RAG vector retrieval note: {rag_err}. Using context chunks.")
        rag_context = "\n---\n".join(chunks[:6])

    # 3. Formulate Prompt
    analysis_prompt = f"""You are an elite Executive Resume Reviewer, ATS Algorithm Specialist, and Technical Hiring Manager.
Analyze the candidate's resume thoroughly using the extracted context below.
CRITICAL INSTRUCTION: Your feedback MUST be highly personalized. Do NOT provide generic advice like "Use the Google XYZ formula" or "Quantify your impact" or "Fix character spacing". You MUST reference specific projects, specific skills, or specific sentences from the candidate's actual resume text. If you suggest an improvement, explain exactly which sentence or section in their resume needs it.

Resume Sections Context:
\"\"\"
{rag_context}
\"\"\"

Full Resume Text Sample:
\"\"\"
{text[:3500]}
\"\"\"

Analyze the resume and return a STRICT, VALID JSON object with the exact keys below. Do NOT output any preamble or extra text.

JSON Schema:
{{
  "overall_score": <number between 0 and 100>,
  "ats_score": <number between 0 and 100>,
  "skill_match": <number between 0 and 100>,
  "issues_found": <integer count of issues>,
  "ai_summary": "<Detailed executive summary evaluating profile strength, career readiness, and competitive edge>",
  "ats_feedback": "<Specific feedback on layout, formatting, headers, and parsing readability>",
  "action_verb_feedback": "<Critique on action verb velocity and proactive achievement phrasing>",
  "bullet_suggestions": [
    {{
      "original": "<A real weak or passive line found in the resume>",
      "improved": "<High-impact rewritten bullet with strong action verb and quantified metric/results>",
      "reason": "<Why this change is stronger>"
    }}
  ],
  "missing_keywords": ["<Specific Keyword 1 missing from their stack>", "<Specific Keyword 2>"],
  "strengths": ["<Specific Strength 1 found in their text>", "<Specific Strength 2>"],
  "improvements": [
    "<Hyper-specific Improvement 1 referencing their actual project/role>", 
    "<Hyper-specific Improvement 2 referencing their actual skills/text>"
  ],
  "parsed_ats_data": [
    {{
      "field": "First Name",
      "status": "found",
      "value": "<Extracted First Name or 'Missing'>"
    }},
    {{
      "field": "Last Name",
      "status": "found",
      "value": "<Extracted Last Name or 'Missing'>"
    }},
    {{
      "field": "Email",
      "status": "found",
      "value": "<Extracted Email or 'Missing'>"
    }},
    {{
      "field": "Phone",
      "status": "found",
      "value": "<Extracted Phone or 'Missing'>"
    }},
    {{
      "field": "LinkedIn URL",
      "status": "found",
      "value": "<Extracted LinkedIn URL or 'Missing'>"
    }},
    {{
      "field": "Education (Degree)",
      "status": "found",
      "value": "<Extracted Highest Degree or 'Missing'>"
    }},
    {{
      "field": "Graduation Year",
      "status": "found",
      "value": "<Extracted Year or 'Missing'>"
    }},
    {{
      "field": "Work Experience 1",
      "status": "found",
      "value": "<Extracted Latest Job Title and Company or 'Missing'>"
    }}
  ]
}}
"""

    # 4. Invoke LLM with fallback
    try:
        print("[AI Service] Invoking Gemini LLM for resume analysis...")
        raw_response = _call_gemini_with_fallback(api_key, analysis_prompt)
        parsed_data = _clean_and_parse_json(raw_response)

        # Validate with Pydantic
        validated = schemas.LLMAnalysisOutput(**parsed_data)
        print("[AI Service] Gemini LLM analysis completed and validated successfully!")
        return validated.model_dump()

    except Exception as llm_err:
        print(f"[AI Service] LLM generation error: {llm_err}. Falling back to heuristic engine.")
        return generate_fallback_heuristic_analysis(text)

# ==========================================
# 7. INTERVIEW PREP GENERATOR
# ==========================================

def generate_interview_questions(analysis: Any) -> Dict[str, Any]:
    api_key = os.getenv("GOOGLE_API_KEY", "").strip()
    if not api_key:
        raise ValueError("No GOOGLE_API_KEY set for interview generation.")

    # Build context from analysis
    context_str = f"AI Summary: {analysis.ai_summary}\n"
    if analysis.strengths:
        context_str += f"Strengths: {analysis.strengths}\n"
    if analysis.parsed_ats_data:
        context_str += f"Extracted Data: {analysis.parsed_ats_data}\n"
    if analysis.missing_keywords:
        context_str += f"Missing/Suggested Skills: {analysis.missing_keywords}\n"
    if analysis.improvements:
        context_str += f"Improvements: {analysis.improvements}\n"
    if analysis.bullet_suggestions:
        context_str += f"Bullet points context: {analysis.bullet_suggestions}\n"

    prompt = f"""You are an elite Technical Hiring Manager conducting an interview based on the candidate's resume.
Your task is to generate EXACTLY 3 highly personalized interview questions for this specific candidate.

Candidate Resume Context:
\"\"\"
{context_str}
\"\"\"

Follow these strict rules:
1. Question 1 (type: "resume_project"): Based directly on something mentioned in the resume (e.g., a project, work experience, achievement, or technical implementation).
2. Question 2 (type: "technical"): Based on one or more technical skills detected from the resume context. Do NOT invent unrelated skills.
3. Question 3 (type: "job_role"): Infer the target job role from the resume context and ask a role-specific question that matches the candidate's skills and the inferred role's standard requirements.

Output the result strictly as a valid JSON object matching this schema:
{{
  "questions": [
    {{
      "type": "resume_project",
      "question": "...",
      "reason": "..."
    }},
    {{
      "type": "technical",
      "question": "...",
      "reason": "..."
    }},
    {{
      "type": "job_role",
      "question": "...",
      "reason": "..."
    }}
  ]
}}

Do NOT output any additional text, preamble, or markdown blocks, only the JSON. 
Make the questions reasonable for a real technical interview (Medium to Medium/Hard difficulty). 
Ensure the questions are distinct and highly specific to the candidate.
"""
    try:
        raw_response = _call_gemini_with_fallback(api_key, prompt)
        parsed_data = _clean_and_parse_json(raw_response)
        
        # Validate structure
        if isinstance(parsed_data, list):
            parsed_data = {"questions": parsed_data}
            
        if "questions" not in parsed_data or len(parsed_data["questions"]) != 3:
            # Fallback if structure is violated
            print("[AI Service] Invalid questions length, attempting repair.")
            questions = parsed_data.get("questions", [])
            while len(questions) < 3:
                questions.append({
                    "type": "technical",
                    "question": "Based on your resume, how do you handle complex technical problem-solving?",
                    "reason": "General technical problem solving assessment."
                })
            parsed_data["questions"] = questions[:3]

        validated = schemas.InterviewPrepResponse(**parsed_data)
        return validated.model_dump()
    except Exception as e:
        print(f"[AI Service] Interview Generation Error: {e}")
        raise RuntimeError("Failed to generate interview questions.")

# ==========================================
# 8. SKILL ROADMAP GENERATOR
# ==========================================

def generate_skill_roadmap_data(analysis: Any, target_role: str) -> Dict[str, Any]:
    api_key = os.getenv("GOOGLE_API_KEY", "").strip()
    if not api_key:
        raise ValueError("No GOOGLE_API_KEY set for roadmap generation.")

    # Build context from analysis
    context_str = f"AI Summary: {analysis.ai_summary}\n"
    if analysis.strengths:
        context_str += f"Current Strong Skills: {analysis.strengths}\n"
    if analysis.missing_keywords:
        context_str += f"Missing Skills: {analysis.missing_keywords}\n"
    if analysis.parsed_ats_data:
        context_str += f"Extracted Data: {analysis.parsed_ats_data}\n"

    prompt = f"""You are an elite Career Coach and Technical Mentor.
Your task is to generate a highly personalized Skill Learning Roadmap for this specific candidate.

Candidate Resume Context:
\"\"\"
{context_str}
\"\"\"

Target Job Role: {target_role}

Follow these strict rules:
1. Identify the gap between the candidate's Current Skills and the Required Skills for the '{target_role}' role.
2. Generate a personalized learning roadmap consisting of logical phases (e.g., Phase 1: Foundation, Phase 2: Core Skills, etc.).
3. Each phase must contain a list of skills to learn.
4. For each skill, provide:
   - name: The specific skill/tool name
   - priority: 'HIGH', 'MEDIUM', or 'LOW'
   - status: Set this to 'Not Started'
   - rationale: Why they need this for '{target_role}'
   - prerequisites: Array of prior skills needed
   - estimated_time: e.g., '2 weeks', '1 month'
   - project_suggestion: A specific practice project to master it.
5. Provide a realistic match_score (0.0 to 100.0) representing how close the candidate currently is to the target role.

Output the result strictly as a valid JSON object matching this schema:
{{
  "target_role": "{target_role}",
  "match_score": 65.5,
  "phases": [
    {{
      "phase": 1,
      "title": "Foundation",
      "skills": [
        {{
          "name": "Python",
          "priority": "HIGH",
          "status": "Not Started",
          "rationale": "...",
          "prerequisites": [],
          "estimated_time": "...",
          "project_suggestion": "..."
        }}
      ]
    }}
  ]
}}

Do NOT output any additional text, preamble, or markdown blocks, only the JSON. 
Make the roadmap logical, progressive, and highly specific to the candidate.
"""
    try:
        raw_response = _call_gemini_with_fallback(api_key, prompt)
        parsed_data = _clean_and_parse_json(raw_response)

        validated = schemas.SkillRoadmapResponse(**parsed_data)
        return validated.model_dump()
    except Exception as e:
        print(f"[AI Service] Roadmap Generation Error: {e}")
        raise RuntimeError("Failed to generate skill roadmap.")
